# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import artists_pb2 as artists__pb2


class ArtistsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtistName = channel.unary_unary(
                '/Artists/GetArtistName',
                request_serializer=artists__pb2.ArtistId.SerializeToString,
                response_deserializer=artists__pb2.Artist.FromString,
                )


class ArtistsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetArtistName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtistsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArtistName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtistName,
                    request_deserializer=artists__pb2.ArtistId.FromString,
                    response_serializer=artists__pb2.Artist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Artists', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Artists(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArtistName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Artists/GetArtistName',
            artists__pb2.ArtistId.SerializeToString,
            artists__pb2.Artist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
