# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artists.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2
import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='artists.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rartists.proto\x1a\x0b\x65nums.proto\x1a\x0c\x61ssets.proto\"\x1b\n\x08\x41rtistId\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\xcb\x01\n\x06\x41rtist\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x1b\n\x08location\x18\x03 \x01(\x0b\x32\t.Location\x12\x15\n\x05price\x18\x04 \x01(\x0b\x32\x06.Price\x12\"\n\x0c\x63ontact_info\x18\x05 \x01(\x0b\x32\x0c.ContactInfo\x12\x17\n\x06rating\x18\x06 \x01(\x0e\x32\x07.Rating\x12\x15\n\x05genre\x18\x07 \x01(\x0e\x32\x06.Genre\x12\x15\n\rbooking_count\x18\x08 \x01(\x05\x32.\n\x07\x41rtists\x12#\n\rGetArtistName\x12\t.ArtistId\x1a\x07.Artistb\x06proto3'
  ,
  dependencies=[enums__pb2.DESCRIPTOR,assets__pb2.DESCRIPTOR,])




_ARTISTID = _descriptor.Descriptor(
  name='ArtistId',
  full_name='ArtistId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ArtistId.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=71,
)


_ARTIST = _descriptor.Descriptor(
  name='Artist',
  full_name='Artist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Artist.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='Artist.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='Artist.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='Artist.price', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contact_info', full_name='Artist.contact_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='Artist.rating', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Artist.genre', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='booking_count', full_name='Artist.booking_count', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=277,
)

_ARTIST.fields_by_name['location'].message_type = assets__pb2._LOCATION
_ARTIST.fields_by_name['price'].message_type = assets__pb2._PRICE
_ARTIST.fields_by_name['contact_info'].message_type = assets__pb2._CONTACTINFO
_ARTIST.fields_by_name['rating'].enum_type = enums__pb2._RATING
_ARTIST.fields_by_name['genre'].enum_type = enums__pb2._GENRE
DESCRIPTOR.message_types_by_name['ArtistId'] = _ARTISTID
DESCRIPTOR.message_types_by_name['Artist'] = _ARTIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArtistId = _reflection.GeneratedProtocolMessageType('ArtistId', (_message.Message,), {
  'DESCRIPTOR' : _ARTISTID,
  '__module__' : 'artists_pb2'
  # @@protoc_insertion_point(class_scope:ArtistId)
  })
_sym_db.RegisterMessage(ArtistId)

Artist = _reflection.GeneratedProtocolMessageType('Artist', (_message.Message,), {
  'DESCRIPTOR' : _ARTIST,
  '__module__' : 'artists_pb2'
  # @@protoc_insertion_point(class_scope:Artist)
  })
_sym_db.RegisterMessage(Artist)



_ARTISTS = _descriptor.ServiceDescriptor(
  name='Artists',
  full_name='Artists',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=279,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetArtistName',
    full_name='Artists.GetArtistName',
    index=0,
    containing_service=None,
    input_type=_ARTISTID,
    output_type=_ARTIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTISTS)

DESCRIPTOR.services_by_name['Artists'] = _ARTISTS

# @@protoc_insertion_point(module_scope)
