USE mysql;
CREATE DATABASE IF NOT EXISTS tidalsurfartist;
USE tidalsurfartist;

CREATE USER IF NOT EXISTS 'user'@'localhost';
GRANT SELECT, INSERT, UPDATE, CREATE, ALTER ON tidalsurfartist.* TO 'user'@'localhost';

ALTER USER 'user'@'localhost' IDENTIFIED BY 'password';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS contact_info;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS  artist(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
city INTEGER NOT NULL,
price INTEGER NOT NULL, -- in cents
pricing_type INTEGER NOT NULL,
email VARCHAR(50),
phone VARCHAR(20),
website VARCHAR(20),
rating INTEGER NOT NULL,
genre INTEGER NOT NULL,
booking_count INTEGER NOT NULL
);