USE mysql;
CREATE DATABASE IF NOT EXISTS tidalsurfbooker;
USE tidalsurfbooker;

CREATE USER IF NOT EXISTS 'user'@'localhost';
GRANT SELECT, INSERT, UPDATE, CREATE, ALTER ON tidalsurfbooker.* TO 'user'@'localhost';

ALTER USER 'user'@'localhost' IDENTIFIED BY 'password';

DROP TABLE IF EXISTS booker;

CREATE TABLE IF NOT EXISTS  booker(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
location_id INTEGER NOT NULL UNIQUE,
asking_price_id INTEGER NOT NULL UNIQUE,
contact_info_id INTEGER NOT NULL UNIQUE,
rating INTEGER NOT NULL,
booking_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS location(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
longitude FLOAT,
latitude FLOAT,
FOREIGN KEY (id) REFERENCES booker(location_id)
);

CREATE TABLE IF NOT EXISTS price(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
price INTEGER NOT NULL, -- in cents
pricing_type INTEGER NOT NULL,
FOREIGN KEY (id) REFERENCES booker(asking_price_id)
);

CREATE TABLE IF NOT EXISTS contact_info(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(50),
phone VARCHAR(20),
website VARCHAR(20),
FOREIGN KEY (id) REFERENCES booker(contact_info_id)
);
